apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"spring-dex-test:latest","namespace":"test"},"fieldPath":"spec.template.spec.containers[?(@.name==\"spring-dex-test\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-11-20T20:46:22Z"
  generation: 2
  labels:
    app: spring-dex-test
    app.kubernetes.io/component: spring-dex-test
    app.kubernetes.io/instance: spring-dex-test
  name: spring-dex-test
  namespace: test
  resourceVersion: "608144829"
  uid: 8999b72c-e91b-4d9b-a005-96889fdddef4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: spring-dex-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: spring-dex-test
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/test/spring-dex-test@sha256:9176536a88d05437ddb28196fb769f1d998a069479c02c116c1a0696b3a0e207
        imagePullPolicy: IfNotPresent
        name: spring-dex-test
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command: ["/usr/local/bin/dex","serve","/dex-config/dex-config.yaml"]
        image: registry.redhat.io/openshift-gitops-1/dex-rhel8@sha256:9116e1adc24db19136ea34b8faeba3b1003228621d81b716cbe4ec4d61ad6ffd
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/live
            port: 5558
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: dex
        ports:
        - containerPort: 5556
          name: http
          protocol: TCP
        - containerPort: 5557
          name: grpc
          protocol: TCP
        - containerPort: 5558
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - mountPath: /dex-config
          name: dex-config
      serviceAccount: dex-server
      serviceAccountName: dex-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dex-config
        configMap:
          defaultMode: 420
          name: dex-config
