apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: spring-dex-test
  name: openjdk-21
  namespace: test
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: registry.redhat.io/ubi8/openjdk-21
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/openjdk-21
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
